language: go

go:
    - 1.5
    - 1.3.3

install:
    - go get -v github.com/nnev/website/termine
    - go get -v github.com/nnev/website/c14h

script:
    - go test ./...

notifications:
    email: false

sudo: false
